package com.zhennan.entity;

import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.StudentNo
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private Integer studentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.LoginPwd
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.StudentName
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private String studentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Sex
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private Boolean sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.GradeId
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private Integer gradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Phone
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Address
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.BornDate
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private Date borndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.Email
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.IdentityCard
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    private String identitycard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.StudentNo
     *
     * @return the value of student.StudentNo
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public Integer getStudentno() {
        return studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.StudentNo
     *
     * @param studentno the value for student.StudentNo
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setStudentno(Integer studentno) {
        this.studentno = studentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.LoginPwd
     *
     * @return the value of student.LoginPwd
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.LoginPwd
     *
     * @param loginpwd the value for student.LoginPwd
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.StudentName
     *
     * @return the value of student.StudentName
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.StudentName
     *
     * @param studentname the value for student.StudentName
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Sex
     *
     * @return the value of student.Sex
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Sex
     *
     * @param sex the value for student.Sex
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.GradeId
     *
     * @return the value of student.GradeId
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public Integer getGradeid() {
        return gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.GradeId
     *
     * @param gradeid the value for student.GradeId
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setGradeid(Integer gradeid) {
        this.gradeid = gradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Phone
     *
     * @return the value of student.Phone
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Phone
     *
     * @param phone the value for student.Phone
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Address
     *
     * @return the value of student.Address
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Address
     *
     * @param address the value for student.Address
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.BornDate
     *
     * @return the value of student.BornDate
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public Date getBorndate() {
        return borndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.BornDate
     *
     * @param borndate the value for student.BornDate
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setBorndate(Date borndate) {
        this.borndate = borndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.Email
     *
     * @return the value of student.Email
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.Email
     *
     * @param email the value for student.Email
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.IdentityCard
     *
     * @return the value of student.IdentityCard
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public String getIdentitycard() {
        return identitycard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.IdentityCard
     *
     * @param identitycard the value for student.IdentityCard
     *
     * @mbggenerated Thu Apr 08 18:45:57 EDT 2021
     */
    public void setIdentitycard(String identitycard) {
        this.identitycard = identitycard;
    }
}